PROJECT_ROOT = "C:\\Users\\44365\PycharmProjects\\bankRPA\\"
DATA_ROOT = "D:\\data\\"
DOWNLOAD_TEMP_DIR = DATA_ROOT + "temp\\"
DOWNLOAD_DIR = DATA_ROOT + "download\\"
UPLOAD_PATH =  DATA_ROOT + "upload\\"
PORT_NUMBER_WEB = 8080
PORT_NUMBER_DD = 8888

IMPLICITLY_WAIT = 5
SCRIPT_TIMEOUT = 5
