PROJECT_ROOT = "C:\\Users\\44365\PycharmProjects\\bankRPA\\"
# PROJECT_ROOT = "D:\\caika\\rpa\\"
# DATA_ROOT = "D:\\data\\"
DATA_ROOT = "D:\\caika\\data\\"

DOWNLOAD_TEMP_DIR = DATA_ROOT + "temp\\"
DOWNLOAD_DIR = DATA_ROOT + "download\\"
UPLOAD_PATH =  DATA_ROOT + "upload\\"
PORT_NUMBER_WEB = 8080
PORT_NUMBER_DD = 8888

IMPLICITLY_WAIT = 10
SCRIPT_TIMEOUT = 10
# PAGELOAD_TIMEOUT = 10
